---
title: "DCS 375 Final Writeup"
author: "Dieter Villegas, Liza Dubinsky, Quinn Macauley, Jenniflore Beaubrun"
date: "4/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final project for DCS 375 on France's Players in the 2018 World Cup Semi-Final and Final


### Introduction 

In this project, we used Statsbomb event data from the [Dato-Futbol/passing-networks GitHub repository](https://github.com/Dato-Futbol/passing-networks) to analyze the final and semi-final games in the 2018 World Cup. Motivated by scholarly articles on constructing and analyzing passing networks, we used network analysis to explore the following questions:

1. What players are central to the directed networks of the France-Croatia final and France-Belgium semi-final? What positions do they play?
2. How are the number of passes allocated across players on each team? 


### Background 

2. Sufficient background to make the significance of your question legible for non-expert readers:
Soccer background, motivation for question and why our question/hypotheses are significant

### Methodology and Discussion 

#### Filtering the Data 

Filter for specific games, writing .csv files, removing extraneous players

#### Creating Network Objects

Creating edgelists of passes to and from players on each team in both games

#### Visualizing Directed Networks

Code and process for visualizing directed networks on soccer fields, color and shape of nodes by player position (include code snippets and interpretation)

[Final Field Croatia.](final_field_croatia.png)

[Final Field France.](final_field_france.png)

#### Centrality and Betweenness 

Code and calculations for exploratory statistics (include code snippets and interpretation)

#### Modeling 

Creating barplots based on position, fit power law distribution and calculate p-values (include code snippets and interpretation)

Null model of power-law distribution, calculate p-value associated with fit of pass distribution histogram to preferential attachment

[Final France Received Passes.](final_france_received_passes.png)

[Final France Sent Passes.](final_france_sent_passes.png)

[Final Croatia Received Passes.](final_croatia_received_passes.png)

[Final Croatia Sent Passes.](final_croatia_sent_passes.png)


5. References to at least four pieces of scholarly writing (these should include readings from the disciplinary or domain space that your question is in, as well as network theory readings from the course)

1. Football passing networks using R (https://www.datofutbol.cl/passing-networks-r/)
2. Using Network Science to Analyse Football Passing Networks: Dynamics, Space, Time, and the Multilayer Nature of the Game (https://www.frontiersin.org/articles/10.3389/fpsyg.2018.01900/full)
3. A network theory analysis of football strategies (https://arxiv.org/pdf/1206.6904.pdf)
4. Play-by-Play Network Analysis in Football (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6669815/)
5. Player position relationships with centrality in the passing network of world cup soccer teams: Win/loss match comparisons (https://reader.elsevier.com/reader/sd/pii/S0960077920300242?token=8E57B44BFF232C5A65695EB10963EC50F09AA44F926BA77E421EA97D4C50493E29D978F1D360149CC7A674D5CF2994E8&originRegion=us-east-1&originCreation=20220405191913)

6. Your data (original github repository and .csv files)








