---
title: "Final Project DCS 375"
author: "Dieter Villegas, Liza Dubinsky, Quinn Macauley "
date: "4/6/2022"
output: html_document
---


```{r load-libraries}
library(dplyr)
library(igraph) 
```


```{r clean-data}

# read in the RDS
wc_rds <- readRDS("/Users/Liza/Desktop/DCS-Futbol-Analysis/WC_events_clean.RDS")

# grab only the columns we're interested in for analysis
wc_maxtrix <- cbind(wc_rds$period,wc_rds$timestamp, wc_rds$duration,wc_rds$possession_team.name,wc_rds$type.name,wc_rds$player.name,wc_rds$team.name,wc_rds$pass.length,wc_rds$pass.recipient.name,wc_rds$pass.outcome.name,wc_rds$ball_receipt.outcome.name,wc_rds$match_id,wc_rds$location.x,wc_rds$location.y,wc_rds$pass.end_location.x,wc_rds$pass.end_location.y)

# turn into a dataframe
wc_df_official <- as.data.frame(wc_maxtrix)

# rename the columns for analysis
colnames(wc_df_official) <- c("period","timestamp","duration","possession_team.name","type.name","player.name","team.name","pass.length","pass.recipient.name","pass.outcome.name","ball_receipt.outcome.name","match_id","location.x","location.y","pass.end_location.x","pass.end_location.y")

# grab only the passes
network_passes <- subset(wc_df_official, type.name == "Pass")

# create 4 data sets for four games we plan to analyze
france_croatia_final <- subset(network_passes, possession_team.name == c("France", "Croatia"))

france_belgium_semi <- subset(network_passes, team.name == c("France", "Belgium"))

france_uruguay_quarter <- subset(network_passes, team.name == c("France", "Uruguay"))

france_argentina_round <- subset(network_passes, team.name == c("France", "Argentina"))

# write 4 csv files for each of these games

write.csv(france_croatia_final, "france_croatia_final.csv", row.names = FALSE)

write.csv(france_belgium_semi, "france_belgium_semi.csv", row.names = FALSE)

write.csv(france_uruguay_quarter, "france_uruguay_quarter.csv", row.names = FALSE)

write.csv(france_argentina_round, "france_argentina_round.csv", row.names = FALSE)

```

```{r france-final-object}

# clean the data frame to only include passes from france and croatia final
team_name_france_croatia_final <- subset(france_croatia_final, team.name == c("France", "Croatia"))

france_only_final <- subset(team_name_france_croatia_final, team.name == "France")

croatia_only_final <- subset(team_name_france_croatia_final, team.name == "Croatia")

# construct dataset for connected passes only 
connected_pass_france_final <- subset(france_only_final, is.na(pass.outcome.name))
connected_pass_croatia_final <- subset(croatia_only_final, is.na(pass.outcome.name))

# create an edgelist of passes to and from players
france_final <- cbind(connected_pass_france_final$player.name, connected_pass_france_final$pass.recipient.name)

croatia_final <- cbind(connected_pass_croatia_final$player.name, connected_pass_croatia_final$pass.recipient.name)

# name these columns
colnames(france_final) <- c("from", "to")
colnames(croatia_final) <- c("from", "to")

# create a graph object for network analysis
france_final.g <- graph.edgelist(france_final, directed = TRUE) # makes a graph object
croatia_final.g <- graph.edgelist(croatia_final, directed = TRUE) # makes a graph object

png(file="france_final.png", width=1000, height=1000)
plot(france_final.g, )
png(file="croatia_final.png", width=1000, height=1000)
plot(croatia_final.g)
dev.off()
```

```{r identify-france-players}

france_midfielder <- c("Corentin Tolisso", "Paul Pogba", "N''Golo Kanté", "Blaise Matuidi", "Steven N''Kemboanza Mike Christopher Nzonzi", "Thomas Lemar", "Florian Thauvin")
france_defender <- c("Benjamin Pavard", "Samuel Yves Umtiti", "Raphaël Varane", "Lucas Hernández Pi", "Presnel Kimpembe", "Djibril Sidibé", "Benjamin Mendy")
france_forward <- c("Ousmane Dembélé", "Kylian Mbappé Lottin", "Antoine Griezmann", "Nabil Fekir", "Olivier Giroud")
france_goalkeeper <- c("Hugo Lloris", "Steve Mandanda")
```

```{r identify-croatia-players}

croatia_midfielder <- c("Luka Modrić", "Ivan Perišić", "Mateo Kovačić", "Marcelo Brozović","Ivan Rakitić", "Milan Badelj", "Filip Bradarić")
croatia_defender <- c("Domagoj Vida", "Dejan Lovren", "Šime Vrsaljko", "Duje Ćaleta-Car", "Ivan Strinić", "Josip Pivarić", "Tin Jedvaj", "Vedran Ćorluka")
croatia_forward <- c("Ante Rebić", "Andrej Kramarić", "Marko Pjaca", "Mario Mandžukić")
croatia_goalkeeper <- c("Lovre Kalinić", "Danijel Subašić")
```
